name: lint_python
on:
  push:
    paths:
      - '*.py'
      - 'lib/**.py'
      - '.github/workflows/lint_python.yml'
  pull_request:
    paths:
    - '*.py'
    - 'lib/**.py'
    - '.github/workflows/lint_python.yml'
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
      - run: ./deploy.sh
      - run: |
          wget https://raw.githubusercontent.com/c0m4r/okrutnik/main/okrutnik.sh
          chmod +x okrutnik.sh
          ./okrutnik.sh --install
      - run: ./okrutnik.sh lib/*.py || true
      - run: ./okrutnik.sh upgrader.py
      - run: ./okrutnik.sh client.py
      - run: ./okrutnik.sh loki.py || true
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install --upgrade bandit black codespell mypy pylint pyright pylama ruff
      - run: ruff . || true
      - run: black --diff . || true
      - run: codespell --skip="./.git/*" --skip="./signature-base" --skip="./lib/python3*" --skip="./venv"
      - run: pip install -r requirements.txt
      - run: mypy --install-types --non-interactive --strict --exclude 'lib64' . || true
      - run: pylama *.py lib/*.py || true
      - run: pylint *.py lib/*.py || true
      - run: pyright . || true
      - run: safety check --ignore 62044
      - run: timeout -s TERM 10 ./loki.py -d || true
      - run: ./loki.py --noprocs --noindicator --dontwait --debug -p ./test
      - run: ./loki.py --noprocs --noindicator --dontwait --debug --intense -p ./test
      - run: ./loki.py --noprocs --noindicator --dontwait --debug --csv -p ./test
