name: lint_python
on:
  push:
    paths:
      - '*.py'
      - 'lib/**.py'
      - '.github/workflows/lint_python.yml'
  pull_request:
    paths:
    - '*.py'
    - 'lib/**.py'
    - '.github/workflows/lint_python.yml'
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - run: ./deploy.sh
      - run: |
          wget https://raw.githubusercontent.com/c0m4r/okrutnik/main/okrutnik.sh
          chmod +x okrutnik.sh
          ./okrutnik.sh --install -r requirements.txt
      - run: ./okrutnik.sh lib/*.py || true
      - run: ./okrutnik.sh --stop lib/paranoya_constants.py
      - run: ./okrutnik.sh --stop lib/paranoya_args.py
      - run: ./okrutnik.sh --stop lib/paranoya_venv.py
      - run: ./okrutnik.sh --stop upgrader.py || true
      - run: ./okrutnik.sh --stop client.py
      - run: ./okrutnik.sh paranoya.py || true
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install --upgrade bandit black codespell mypy pylint pyright pylama ruff safety
      - run: ruff .
      - run: black --diff .
      - run: codespell -L paranoya --skip="./.git/*" --skip="./signature-base" --skip="./lib/python3*" --skip="./venv"
      - run: pip install -r requirements.txt
      - run: mypy --install-types --non-interactive --strict --exclude 'lib64' . || true
      - run: pylama *.py lib/*.py || true
      - run: pylint *.py lib/*.py || true
      - run: pyright . || true
      - run: safety check --ignore 62044
      - run: ./paranoya.py -d &
      - run: sleep 5
      - run: ./client.py -p LICENSE
      - run: ./client.py -p ./test
      - run: kill -TERM $(cat paranoya.pid)
      - run: ./paranoya.py --noprocs --noindicator --dontwait --debug -p ./test
      - run: ./paranoya.py --noprocs --noindicator --dontwait --debug --intense -p ./test
      - run: ./paranoya.py --noprocs --noindicator --dontwait --debug --csv -p ./test
